# Cores inspiradas no Elementary OS
foreground = "#d8dee9"
background = "#1e1e2e"  # fundo escuro elegante com leve transparência ativada via config
selection-foreground = "#ffffff"
selection-background = "#4c566a"

cursor = "#88c0d0"
cursor-text = "#2e3440"

# Paleta básica
[palette]
black = "#2e3440"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#e5e9f0"

bright-black = "#4c566a"
bright-red = "#bf616a"
bright-green = "#a3be8c"
bright-yellow = "#ebcb8b"
bright-blue = "#81a1c1"
bright-magenta = "#b48ead"
bright-cyan = "#8fbcbb"
bright-white = "#eceff4"
